version: "3.6"
services:
  # MySQL Container
  mariadb:
    # Container Name
    container_name: ${MYSQL_CONTAINER_NAME}
    # Image of MySQL Container
    image: mariadb
    # Loaded Environment Variables
    env_file: .env
    # Seting Environment Variables
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # Setting the folder of container
    volumes:
      - ./${SRC_DATA_DIR}/database:/var/lib/mysql
    # Setting ports of container
    ports:
      - ${MYSQL_LOCALHOST_PORT}:3306
    networks:
      - wordpress_network
    restart: unless-stopped

  # Wordpress Container
  wordpress:
    # Container Name
    container_name: ${WORDPRESS_CONTAINER_NAME}
    # Image of Wordpress Container
    image: wordpress:latest
    # Loaded Environment Variables
    env_file: .env
    # Seting Environment Variables
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DB_HOST: ${MYSQL_CONTAINER_NAME}:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', '${MACHINE_HOST}:${WORDPRESS_LOCALHOST_PORT}');
        define('WP_SITEURL', '${MACHINE_HOST}:${WORDPRESS_LOCALHOST_PORT}');
    # Setting the folder of container
    volumes:
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./${SRC_DATA_DIR}/wordpress:/var/www/html
      - ./config/phpinfo.php:/var/www/html/phpinfo.php
    # Setting ports of container
    ports:
      - ${WORDPRESS_LOCALHOST_PORT}:80
    depends_on:
      - mariadb
    links:
      - mariadb
    networks:
      - wordpress_network
    restart: unless-stopped

  # PhpMyAdmin Container
  phpmyadmin:
    # Container Name
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    # Image of Wordpress Container
    image: phpmyadmin/phpmyadmin
    # Setting ports of container
    ports:
      - ${PHPMYADMIN_LOCALHOST_PORT}:80
    # Loaded Environment Variables
    env_file: .env
    # Seting Environment Variables
    environment:
      PMA_HOST: ${MYSQL_CONTAINER_NAME}:${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mariadb
    networks:
      - wordpress_network
    restart: unless-stopped

  # Wordpress Client Container
  wpcli:
    # Container Name
    container_name: ${WPCLI_CONTAINER_NAME}
    # Image of WPCLI Container
    image: wordpress:cli
    # Loaded Environment Variables
    env_file: .env
    command: /bin/sh ./wp-cli-config.sh
    volumes:
      - ./${SRC_DATA_DIR}/wordpress:/var/www/html
      - ./scripts/wp-cli/wp-cli-config.sh:/var/www/html/wp-cli-config.sh
    working_dir: /var/www/html
    depends_on:
      - wordpress
      - mariadb
    environment:
      # Waiting for MySQL and wordpress -------------------
      - WAIT_HOSTS=${MYSQL_CONTAINER_NAME}:3306,${WORDPRESS_CONTAINER_NAME}:80
      - WAIT_BEFORE_HOSTS=${WAIT_BEFORE_HOSTS:-30}
      - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS:-15}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT:-300}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL:-30}
      - WAIT_HOST_CONNECT_TIMEOUT=${WAIT_HOST_CONNECT_TIMEOUT:-30}
    networks:
      - wordpress_network
    restart: unless-stopped
    user: 1000:1000

networks:
  wordpress_network:
    name: wordpress_network
